version: '3'

networks:
  default:
    external:
      name: tradingpulse

services:

  stg-sourcedata:
    image: ageworks/sourcedata.service
    hostname: stg-sourcedata
    container_name: stg-sourcedata
    environment:
      # Note: as workaround for https://github.com/micronaut-projects/micronaut-kafka/issues/179
      # you need to declare all kafka.* properties in dot notation as well
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - kafka.bootstrap.servers=kafka:29092 
   
  stg-indicators:
    image: ageworks/indicators.service
    hostname: stg-indicators
    container_name: stg-indicators
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - kafka.bootstrap.servers=kafka:29092 
    depends_on:
      - stg-sourcedata
         
  stg-systems:
    image: ageworks/systems.service
    hostname: stg-systems
    container_name: stg-systems
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - kafka.bootstrap.servers=kafka:29092 
    depends_on:
      - stg-indicators
   
  stg-tradingscreens:
    image: ageworks/tradingscreens.service
    hostname: stg-tradingscreens
    container_name: stg-tradingscreens
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - kafka.bootstrap.servers=kafka:29092 
    depends_on:
      - stg-systems
   
  stg-connect:
    image: ageworks/iexcloud
    hostname: stg-connect
    container_name: stg-connect
    depends_on:
      - stg-sourcedata
    ports:
      - "8083:8083"
         