version: '3'

networks:
  default:
    external:
      name: tradingpulse
      
services:

  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=APP_NET://:29092,HOST://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=APP_NET:PLAINTEXT,HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=APP_NET://kafka:29092,HOST://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=APP_NET
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DIR_ZOOKEEPER_DATA}"
      
  kafka_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${DIR_KAFKA_DATA}"
    